name: github pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '17.x'

    - name: Cache dependencies
      uses: actions/cache@v2
      id: yarn-cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: install
      run: yarn install --frozen-lockfile
      working-directory: ./portfolio

    - name: build
      run: yarn build
      working-directory: ./portfolio

    - name: export
      run: yarn export
      working-directory: ./portfolio

    - name: add nojekyll
      run: touch out/.nojekyll
      working-directory: ./portfolio

    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./portfolio/out
