name: GitHub-Profile-Summary-Cards

on:
  schedule: # execute every 24 hours
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    paths-ignore:
      - 'portfolio/**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate

    steps:
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMRY_CARDS_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          UTC_OFFSET: 9
